pacs:
  hostname: 172.29.144.1
  port: 4242
  aet: ORTHANC
local:
  port: 4000
  aet: SAMPLE_AE
request:
  type: c-find
  model: patient
  threads: 1
  throttle_time: 0.0
  elements_batch_file: /home/pascal/pydicom-batch/config/sample-c-find-batch.csv
  elements:
    - PatientID
    - PatientName
    - PatientSex
    - StudyTime
    - StudyDate
    - AccessionNumber
    - StudyInstanceUID
    - QueryRetrieveLevel=STUDY
    - (0008,0061)
    - (0020,1208)
    - (0020,1206)
    - (0008,1030)
output:
  anonymization_script: /home/pascal/pydicom-batch/config/sample-dicom-anonymizer.script
  anonymization_lookup_table: /home/pascal/pydicom-batch/config/sample-lookup-table.properties
  directory: /home/pascal/pydicom-batch/data
  database_file: /home/pascal/pydicom-batch/data/database-c-find.csv
  directory_structure: PatientID/StudyInstanceUID/

  